# Another one
print('should be no error')

def a____():
  return 0